<a href="https://colab.research.google.com/github/benson40/Mini-Project/blob/main/Mini_Project_Image_Classification_using_Sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Gathering Data using bing image downloader

In [1]:
#Installing bing-image-downloader
!pip install bing-image-downloader

In [2]:
!mkdir Images

In [3]:
from bing_image_downloader import downloader
downloader.download("Lion",limit=30,output_dir='Images')



[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://thenationonlineng.net/wp-content/uploads/2019/03/LION.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Gir_lion.jpg/1200px-Gir_lion.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.unilad.co.uk/wp-content/uploads/2015/12/Lion.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://www.zsl.org/sites/default/files/image/2014-05/Asian-lion-in-wild-3.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://www.laketobias.com/wp-content/uploads/2015/02/lion.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://d.ibtimes.co.uk/en/full/1673703/lion-krugger.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://cdn.the-scientist.com/assets/articleNo/64974/iImg/29220/male-asiatic-lion-in-gir-l.png
[%] File Downloaded !

[%] Downloading Image #8 from http://www.pbs.org/wnet/natu

In [4]:
from bing_image_downloader import downloader
downloader.download("Elephant",limit=30,output_dir='Images')



[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/African_Bush_Elephant.jpg/1200px-African_Bush_Elephant.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://scitechdaily.com/images/Sad-African-Elephant.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://geographydirections.files.wordpress.com/2014/11/800px-elephant_near_ndutu.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://sites.psu.edu/siowfa16/files/2016/10/Elephant-wallpaper-26-1l0oc2t.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://elephant-family.org/wp-content/uploads/2015/06/shutterstock_77217466.jpg
[%] File Downloaded !

[%] Downloading Image #6 from http://maraelephantproject.org/wp-content/uploads/2016/09/DSC_0172-e1504880967403.jpg
[%] File Downloaded !

[%] Downloading Image #7 from http://static.horizontimes.com/wp-content/uploads/2017/07/13095652/African-Elephant.jpg


In [5]:
%ls '/content/Images'

Elephant/  Lion/


#Preprocessing the Data

In [6]:
#Importing the libraries
import numpy as np
import pandas as pd
import os 
import matplotlib.pyplot as plt 
from skimage.transform import resize  #basically for resizing the image
from skimage.io import imread

In [7]:
target = [] #output
images = [] #Matrix Format
flat_data = [] #input
DATADIR='/content/Images'

CATEGORIES = ['Elephant','Lion'] #or any other two category

#Reading each file from the images
for i in CATEGORIES:
  class_target = CATEGORIES.index(i)                     #or label encoding the target value
  path=os.path.join(DATADIR,i)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    img_resized=resize(img_array,(150,150,3)) #Scaling down(Flattening) #when you do resizing Skimage normalizes the value
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_target)
    print(img_array.shape)
flat_data = np.array(flat_data)
target=np.array(target)
images=np.array(images)

(630, 1200, 3)
(600, 1000, 3)
(664, 1000, 3)
(1800, 1200, 3)
(1266, 1900, 3)
(1067, 800, 3)
(3219, 4503, 3)
(1406, 2165, 3)
(1333, 2000, 3)
(1200, 1600, 3)
(2991, 4381, 3)
(806, 1200, 3)
(415, 1024, 3)
(1599, 1066, 3)
(1800, 1200, 3)
(1080, 1920, 3)
(600, 900, 3)
(622, 1000, 3)
(1000, 2000, 3)
(1062, 1600, 3)
(900, 1920, 3)
(881, 1280, 3)
(599, 1000, 3)
(1062, 1600, 3)
(899, 1200, 3)
(3779, 3456, 3)
(1049, 2000, 3)
(600, 1000, 3)
(1152, 2048, 3)
(1365, 2048, 3)
(1363, 2048, 3)
(639, 945, 3)
(1000, 2000, 3)
(1875, 2500, 3)
(1797, 2500, 3)
(900, 1600, 3)
(1001, 1500, 3)
(1140, 1600, 3)
(1200, 1200, 3)
(675, 450, 3)
(2160, 4096, 3)
(1074, 736, 3)
(1334, 2000, 3)
(1875, 2500, 3)
(1125, 2000, 3)
(1563, 2400, 3)
(1376, 780, 4)
(1400, 948, 3)
(394, 700, 3)
(1200, 800, 3)
(720, 1280, 3)
(2000, 3008, 3)
(1080, 1920, 3)
(1703, 1200, 4)
(667, 1000, 3)
(1366, 1065, 3)
(823, 1235, 3)
(4614, 3456, 3)
(2832, 4256, 3)
(1275, 1920, 3)


In [8]:
#Creating the Dataframe from the images
df=pd.DataFrame(flat_data)
df['Target'] = target
df

0         1         2  ...     67498     67499  Target
0   0.968627  0.968627  0.968627  ...  0.415294  0.203529       0
1   0.637255  0.686275  0.723529  ...  0.504902  0.394771       0
2   0.671054  0.749020  0.850980  ...  0.546850  0.071137       0
3   0.734314  0.800980  0.836275  ...  0.575490  0.454902       0
4   0.362484  0.362484  0.342693  ...  0.345098  0.203922       0
5   0.319632  0.333728  0.210235  ...  0.418054  0.162092       0
6   0.631373  0.654902  0.728970  ...  0.482353  0.258824       0
7   0.784314  0.807843  0.800000  ...  0.640327  0.424641       0
8   0.686052  0.827673  0.937255  ...  0.516943  0.364039       0
9   0.535294  0.745098  0.858824  ...  0.549020  0.300000       0
10  0.650980  0.713725  0.815686  ...  0.553156  0.343255       0
11  0.623529  0.690196  0.807843  ...  0.439216  0.198405       0
12  0.615686  0.678431  0.729412  ...  0.787778  0.489399       0
13  0.796078  0.718314  0.623356  ...  0.655494  0.423948       0
14  0.734314  0.800980  0.836275  ...  0.575490  0.454902       0
15  0.819608  0.823529  0.842745  ...  0.388627  0.223922       0
16  0.341176  0.535294  0.839216  ...  0.458824  0.301961       0
17  0.568993  0.736601  0.909429  ...  0.476462  0.315399       0
18  0.529412  0.607843  0.772549  ...  0.424837  0.294771       0
19  0.925804  0.909333  0.819765  ...  0.690065  0.682850       0
20  0.780392  0.819608  0.858824  ...  0.474902  0.267059       0
21  0.466667  0.549020  0.801313  ...  0.175176  0.132039       0
22  0.615686  0.694118  0.792157  ...  0.090837  0.048028       0
23  0.588235  0.796078  0.929412  ...  0.513072  0.341020       0
24  0.315634  0.396013  0.481314  ...  0.519582  0.381353       0
25  0.231373  0.388235  0.203922  ...  0.890204  0.494039       0
26  0.956863  0.992157  0.996078  ...  0.570627  0.285634       0
27  0.870588  0.874510  0.882353  ...  0.494444  0.284641       0
28  0.147686  0.188235  0.167294  ...  0.470153  0.272226       0
29  0.314627  0.340209  0.246092  ...  0.309033  0.269229       0
30  0.784314  0.678601  0.537425  ...  0.607843  0.517817       1
31  0.180469  0.310745  0.185333  ...  0.254824  0.227373       1
32  0.293464  0.325490  0.313725  ...  0.254902  0.266558       1
33  0.600000  0.607843  0.521569  ...  0.635294  0.509804       1
34  0.521569  0.472843  0.407843  ...  0.674510  0.768627       1
35  0.733333  0.831373  0.921569  ...  0.655556  0.600000       1
36  0.874510  0.909804  0.929412  ...  0.411765  0.291837       1
37  0.835294  0.850980  0.886275  ...  0.294118  0.136275       1
38  0.117647  0.107843  0.062745  ...  0.423529  0.516667       1
39  0.282353  0.278431  0.316667  ...  0.397059  0.413725       1
40  0.196078  0.164706  0.141176  ...  0.211765  0.188235       1
41  0.937255  0.937255  0.956863  ...  0.078614  0.074211       1
42  0.827660  0.909804  0.972549  ...  0.607190  0.528105       1
43  0.600000  0.607843  0.521569  ...  0.635294  0.509804       1
44  0.776471  0.594608  0.435131  ...  0.364706  0.301961       1
45  0.890196  0.815686  0.737255  ...  0.196078  0.082353       1
46  0.743562  0.553621  0.898806  ...  0.524571  0.892683       1
47  0.639869  0.526144  0.306536  ...  0.555582  0.294340       1
48  0.765133  0.655939  0.419068  ...  0.545455  0.437569       1
49  0.408824  0.466013  0.162092  ...  0.513725  0.566667       1
50  0.117647  0.125490  0.121569  ...  0.133333  0.105882       1
51  0.641416  0.435948  0.149020  ...  0.555900  0.256863       1
52  0.843137  0.866667  0.913725  ...  0.620000  0.325490       1
53  0.675510  0.524049  0.907959  ...  0.512859  0.904402       1
54  0.142664  0.112418  0.077124  ...  0.545320  0.188889       1
55  0.349843  0.330235  0.185114  ...  0.313542  0.243150       1
56  0.858824  0.925490  0.956863  ...  0.562510  0.206196       1
57  0.023529  0.105882  0.086275  ...  0.654980  0.309804       1
58  0.972549  0.956863  0.945098  ...  0.270588  0.098039       1
59  0.380392  0.396078  0.411765  ...  0.765980  0.

In [9]:
flat_data.shape

(60, 67500)

In [10]:
target.shape

(60,)

In [11]:
#Features(x) and Target(y)
x=flat_data 
y=target
x

array([[0.96862745, 0.96862745, 0.96862745, ..., 0.41960784, 0.41529412,
        0.20352941],
       [0.6372549 , 0.68627451, 0.72352941, ..., 0.6130719 , 0.50490196,
        0.39477124],
       [0.67105447, 0.74901961, 0.85098039, ..., 0.45955556, 0.54684967,
        0.07113725],
       ...,
       [0.02352941, 0.10588235, 0.08627451, ..., 0.53333333, 0.65498039,
        0.30980392],
       [0.97254902, 0.95686275, 0.94509804, ..., 0.46805699, 0.27058824,
        0.09803922],
       [0.38039216, 0.39607843, 0.41176471, ..., 0.76480392, 0.76598039,
        0.78862745]])

In [12]:
#Split data into Training and Testing Data

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0,stratify=y)
#stratify distributes it in a proper proportion , we are dividing based on output.
print(x_train.shape)
print(x_test.shape)

(45, 67500)
(15, 67500)


In [13]:
print(y_train.shape)
print(y_test.shape)

(45,)
(15,)


# Applying SVM Algorithm and choosing the best parameters using GridSearch CV

In [14]:
#GridsearchCV for SVM: used to get the best value for the parameters in SVC() like c,gamma and kernel
from sklearn.model_selection import GridSearchCV
from sklearn import svm
parameters=[
            {'C':[1,10,100,1000],'kernel':['linear']},
            {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']},
            {'C':[1,10,100,1000],'kernel':['poly']}
            
]
svc=svm.SVC(probability=True)
cv=GridSearchCV(svc,parameters)
cv.fit(x_train,y_train)
cv.best_params_

{'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}

In [15]:
y_pred=cv.predict(x_test)
y_pred

array([1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0])

In [16]:
y_test

array([1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0])

In [22]:
from sklearn.svm import SVC
model=SVC(C=10,gamma=0.0001) #Using the best parameters that we got from GridSearchCV previously
model.fit(x_train,y_train)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [23]:
y_pred=model.predict(x_test)
y_pred

array([1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0])

#Evaluation of the Model using Confusion Matrix and Classification Report


In [24]:
#Evaluation of the model
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
confusion_matrix(y_pred,y_test)

array([[8, 1],
       [0, 6]])

In [25]:
accuracy_score(y_pred,y_test)*100

93.33333333333333

In [26]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      1.00      0.94         8
           1       1.00      0.86      0.92         7

    accuracy                           0.93        15
   macro avg       0.94      0.93      0.93        15
weighted avg       0.94      0.93      0.93        15



# Predicting for a new Image

In [44]:
data=[]
url=input('Enter your URL')
img=imread(url)
img_resized = resize(img,(150,150,3))
data.append(img_resized.flatten())
data=np.array(data)
plt.imshow(img_resized)
output=model.predict(data)
output=CATEGORIES[output[0]]
print(f'Predicted Output: {output}')

Enter your URLhttps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ68OahgNIZAIXp1L6QAy7ZMQ3MCbLS4etqdQ&usqp=CAU
Predicted Output: Elephant
